/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as todoUsersImport } from './routes/(todo)/users'
import { Route as todoUsersDashboardImport } from './routes/(todo)/users/dashboard'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const todoUsersRoute = todoUsersImport.update({
  id: '/(todo)/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const todoUsersDashboardRoute = todoUsersDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => todoUsersRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/(todo)/users': {
      id: '/(todo)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof todoUsersImport
      parentRoute: typeof rootRoute
    }
    '/(todo)/users/dashboard': {
      id: '/(todo)/users/dashboard'
      path: '/dashboard'
      fullPath: '/users/dashboard'
      preLoaderRoute: typeof todoUsersDashboardImport
      parentRoute: typeof todoUsersImport
    }
  }
}

// Create and export the route tree

interface todoUsersRouteChildren {
  todoUsersDashboardRoute: typeof todoUsersDashboardRoute
}

const todoUsersRouteChildren: todoUsersRouteChildren = {
  todoUsersDashboardRoute: todoUsersDashboardRoute,
}

const todoUsersRouteWithChildren = todoUsersRoute._addFileChildren(
  todoUsersRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/users': typeof todoUsersRouteWithChildren
  '/users/dashboard': typeof todoUsersDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/users': typeof todoUsersRouteWithChildren
  '/users/dashboard': typeof todoUsersDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/(todo)/users': typeof todoUsersRouteWithChildren
  '/(todo)/users/dashboard': typeof todoUsersDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/users' | '/users/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/users' | '/users/dashboard'
  id: '__root__' | '/' | '/about' | '/(todo)/users' | '/(todo)/users/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutRoute: typeof AboutRoute
  todoUsersRoute: typeof todoUsersRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutRoute: AboutRoute,
  todoUsersRoute: todoUsersRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/(todo)/users"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/(todo)/users": {
      "filePath": "(todo)/users.tsx",
      "children": [
        "/(todo)/users/dashboard"
      ]
    },
    "/(todo)/users/dashboard": {
      "filePath": "(todo)/users/dashboard.tsx",
      "parent": "/(todo)/users"
    }
  }
}
ROUTE_MANIFEST_END */
